// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpvr68V202F1bH9jeH_yeiH5bgE_DcwbY',
    appId: '1:1030050973751:web:30a76511dd9fb56df797b2',
    messagingSenderId: '1030050973751',
    projectId: 'restaurantapp-42150',
    authDomain: 'restaurantapp-42150.firebaseapp.com',
    storageBucket: 'restaurantapp-42150.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO1P2D3jVAPBY3QgVtux_oF3k3a1fryfw',
    appId: '1:1030050973751:android:35554527aabfd4c9f797b2',
    messagingSenderId: '1030050973751',
    projectId: 'restaurantapp-42150',
    storageBucket: 'restaurantapp-42150.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9hZhdzno9cjV257B0XasJq5MH9B2S7bA',
    appId: '1:1030050973751:ios:729dead27f54a4e2f797b2',
    messagingSenderId: '1030050973751',
    projectId: 'restaurantapp-42150',
    storageBucket: 'restaurantapp-42150.appspot.com',
    iosClientId: '1030050973751-8sc6ens2cohio3uciq1n8nnsabptni2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
